// 'use client';

// import { useState } from 'react';
// import { motion } from 'framer-motion';
// import { RotateCcw, Download, TrendingDown, Droplets, AlertTriangle, CheckCircle, ChevronDown } from 'lucide-react';
// import type { AnalysisResult, CapturedImages } from '@/app/page';

// interface Props {
//   result: AnalysisResult;
//   images: CapturedImages;
//   onRetake: () => void;
// }

// const LEVEL_CONFIG = [
//   { label: 'No Baldness',       color: '#14b8a6', bg: 'rgba(20,184,166,0.15)',  ring: '#14b8a6' },
//   { label: 'Mild Thinning',     color: '#eab308', bg: 'rgba(234,179,8,0.15)',   ring: '#eab308' },
//   { label: 'Moderate Hair Loss',color: '#f97316', bg: 'rgba(249,115,22,0.15)',  ring: '#f97316' },
//   { label: 'Severe Baldness',   color: '#ef4444', bg: 'rgba(239,68,68,0.15)',   ring: '#ef4444' },
// ];

// function ScoreRing({ score, level }: { score: number; level: number }) {
//   const cfg = LEVEL_CONFIG[level] || LEVEL_CONFIG[0];
//   const r = 70;
//   const circ = 2 * Math.PI * r;
//   const offset = circ * (1 - score / 100);

//   return (
//     <div className="relative w-48 h-48 mx-auto">
//       <svg className="w-full h-full -rotate-90" viewBox="0 0 160 160">
//         <circle cx="80" cy="80" r={r} fill="none" stroke="rgba(255,255,255,0.06)" strokeWidth="12" />
//         <motion.circle
//           cx="80" cy="80" r={r}
//           fill="none"
//           stroke={cfg.ring}
//           strokeWidth="12"
//           strokeDasharray={circ}
//           strokeDashoffset={offset}
//           strokeLinecap="round"
//           initial={{ strokeDashoffset: circ }}
//           animate={{ strokeDashoffset: offset }}
//           transition={{ duration: 1.5, ease: 'easeOut', delay: 0.3 }}
//         />
//       </svg>
//       <div className="absolute inset-0 flex flex-col items-center justify-center">
//         <motion.span
//           className="font-display text-4xl font-bold"
//           style={{ color: cfg.ring }}
//           initial={{ opacity: 0 }}
//           animate={{ opacity: 1 }}
//           transition={{ delay: 0.5 }}
//         >
//           {score}
//         </motion.span>
//         <span className="text-white/40 text-xs font-mono">BALDNESS SCORE</span>
//       </div>
//     </div>
//   );
// }

// function HeatmapArea({ label, value, color }: { label: string; value: number; color: string }) {
//   return (
//     <div className="flex items-center gap-3">
//       <span className="text-white/50 text-xs w-24 text-right">{label}</span>
//       <div className="flex-1 h-2 bg-white/5 rounded-full overflow-hidden">
//         <motion.div
//           className="h-full rounded-full"
//           style={{ backgroundColor: color }}
//           initial={{ width: 0 }}
//           animate={{ width: `${value}%` }}
//           transition={{ duration: 1, delay: 0.8, ease: 'easeOut' }}
//         />
//       </div>
//       <span className="font-mono text-xs w-8" style={{ color }}>{value}%</span>
//     </div>
//   );
// }

// function getAreaColor(value: number) {
//   if (value < 25) return '#14b8a6';
//   if (value < 50) return '#eab308';
//   if (value < 75) return '#f97316';
//   return '#ef4444';
// }

// export default function ResultsDashboard({ result, images, onRetake }: Props) {
//   const [showInsights, setShowInsights] = useState(false);
//   const cfg = LEVEL_CONFIG[result.classification_level] || LEVEL_CONFIG[0];

//   const handleExport = () => {
//     const reportText = `
// ScalpAI Analysis Report
// ========================
// Baldness Score:        ${result.baldness_score}/100
// Hair Density:          ${result.hair_density_percentage}%
// Classification:        ${result.classification}
// Processing Time:       ${result.processing_time}s

// Affected Areas:
//   Top:                 ${result.affected_areas.top}%
//   Crown:               ${result.affected_areas.crown}%
//   Front:               ${result.affected_areas.front}%
//   Left Temple:         ${result.affected_areas.left_temple}%
//   Right Temple:        ${result.affected_areas.right_temple}%

// AI Insights:
// ${result.ai_insights}

// Recommendations:
// ${result.recommendations.map(r => `• ${r}`).join('\n')}

// Generated by ScalpAI — ${new Date().toLocaleString()}
//     `.trim();
//     const blob = new Blob([reportText], { type: 'text/plain' });
//     const url  = URL.createObjectURL(blob);
//     const a    = document.createElement('a');
//     a.href = url; a.download = 'scalp-analysis.txt'; a.click();
//     URL.revokeObjectURL(url);
//   };

//   return (
//     <div className="min-h-screen pb-24">
//       {/* Header */}
//       <div className="glass border-b border-white/5 px-4 py-4 flex items-center justify-between">
//         <span className="font-mono text-sm text-aurora-400 tracking-widest">ANALYSIS COMPLETE</span>
//         <div className="flex gap-2">
//           <button onClick={handleExport} className="p-2 rounded-xl glass hover:bg-white/10 transition-colors">
//             <Download className="w-4 h-4 text-white/60" />
//           </button>
//           <button onClick={onRetake} className="flex items-center gap-2 px-3 py-2 rounded-xl glass hover:bg-white/10 transition-colors text-white/60 text-sm">
//             <RotateCcw className="w-3.5 h-3.5" /> Retake
//           </button>
//         </div>
//       </div>

//       <div className="max-w-lg mx-auto px-4 py-6 space-y-6">

//         {/* Score card */}
//         <motion.div
//           initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
//           className="glass rounded-3xl p-6"
//           style={{ borderColor: `${cfg.ring}30` }}
//         >
//           <ScoreRing score={result.baldness_score} level={result.classification_level} />

//           <div className="text-center mt-4">
//             <motion.div
//               initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.6 }}
//               className="inline-flex items-center gap-2 px-4 py-2 rounded-full text-sm font-semibold"
//               style={{ background: cfg.bg, color: cfg.color }}
//             >
//               {result.classification_level === 0 ? <CheckCircle className="w-4 h-4" /> : <AlertTriangle className="w-4 h-4" />}
//               {result.classification}
//             </motion.div>
//             <p className="text-white/30 text-xs font-mono mt-2">
//               Processed in {result.processing_time}s
//             </p>
//           </div>
//         </motion.div>

//         {/* Stats row */}
//         <motion.div
//           initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15 }}
//           className="grid grid-cols-2 gap-3"
//         >
//           <div className="glass rounded-2xl p-4">
//             <Droplets className="w-5 h-5 text-aurora-400 mb-2" />
//             <p className="text-2xl font-bold text-white">{result.hair_density_percentage}%</p>
//             <p className="text-white/40 text-xs mt-1">Hair Density</p>
//           </div>
//           <div className="glass rounded-2xl p-4">
//             <TrendingDown className="w-5 h-5 text-ember-400 mb-2" />
//             <p className="text-2xl font-bold text-white">{result.baldness_score}</p>
//             <p className="text-white/40 text-xs mt-1">Baldness Index</p>
//           </div>
//         </motion.div>

//         {/* Affected areas heatmap */}
//         <motion.div
//           initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.25 }}
//           className="glass rounded-2xl p-5"
//         >
//           <h3 className="text-white font-semibold mb-4 flex items-center gap-2">
//             <div className="w-1.5 h-4 rounded-full bg-aurora-500" />
//             Affected Areas
//           </h3>
//           <div className="space-y-3">
//             {[
//               { label: 'Top',          value: result.affected_areas.top          },
//               { label: 'Crown',        value: result.affected_areas.crown        },
//               { label: 'Front',        value: result.affected_areas.front        },
//               { label: 'Left Temple',  value: result.affected_areas.left_temple  },
//               { label: 'Right Temple', value: result.affected_areas.right_temple },
//             ].map(a => (
//               <HeatmapArea key={a.label} label={a.label} value={a.value} color={getAreaColor(a.value)} />
//             ))}
//           </div>
//         </motion.div>

//         {/* AI Insights */}
//         <motion.div
//           initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.35 }}
//           className="glass rounded-2xl overflow-hidden"
//         >
//           <button
//             className="w-full p-5 flex items-center justify-between"
//             onClick={() => setShowInsights(!showInsights)}
//           >
//             <h3 className="text-white font-semibold flex items-center gap-2">
//               <div className="w-1.5 h-4 rounded-full bg-plasma" />
//               AI Vision Insights
//             </h3>
//             <ChevronDown className={`w-4 h-4 text-white/40 transition-transform ${showInsights ? 'rotate-180' : ''}`} />
//           </button>
//           {showInsights && (
//             <motion.div
//               initial={{ height: 0, opacity: 0 }}
//               animate={{ height: 'auto', opacity: 1 }}
//               className="px-5 pb-5"
//             >
//               <p className="text-white/60 text-sm leading-relaxed">{result.ai_insights}</p>
//             </motion.div>
//           )}
//         </motion.div>

//         {/* Recommendations */}
//         <motion.div
//           initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.45 }}
//           className="glass rounded-2xl p-5"
//         >
//           <h3 className="text-white font-semibold mb-4 flex items-center gap-2">
//             <div className="w-1.5 h-4 rounded-full bg-ember-400" />
//             Recommendations
//           </h3>
//           <div className="space-y-2">
//             {result.recommendations.map((rec, i) => (
//               <motion.div
//                 key={i}
//                 initial={{ opacity: 0, x: -10 }}
//                 animate={{ opacity: 1, x: 0 }}
//                 transition={{ delay: 0.5 + i * 0.08 }}
//                 className="flex items-start gap-3"
//               >
//                 <div className="w-1.5 h-1.5 rounded-full bg-ember-400 mt-2 flex-shrink-0" />
//                 <p className="text-white/70 text-sm">{rec}</p>
//               </motion.div>
//             ))}
//           </div>
//           <p className="text-white/20 text-xs font-mono mt-4 leading-relaxed">
//             NOT MEDICAL ADVICE. CONSULT A LICENSED DERMATOLOGIST FOR DIAGNOSIS & TREATMENT.
//           </p>
//         </motion.div>

//         {/* Captured thumbnails */}
//         <motion.div
//           initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.55 }}
//           className="glass rounded-2xl p-5"
//         >
//           <h3 className="text-white font-semibold mb-3 text-sm">Captured Images</h3>
//           <div className="grid grid-cols-4 gap-2">
//             {(['front','left','right','top'] as const).map(angle => (
//               <div key={angle} className="aspect-square rounded-xl overflow-hidden border border-white/10">
//                 {images[angle]
//                   ? <img src={images[angle]!} className="w-full h-full object-cover" alt={angle} />
//                   : <div className="w-full h-full bg-white/5 flex items-center justify-center text-white/20 text-xs">{angle}</div>
//                 }
//               </div>
//             ))}
//           </div>
//         </motion.div>

//       </div>
//     </div>
//   );
// }

'use client';

import { useState, useEffect, useRef, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { RotateCcw, Download, TrendingDown, Droplets, AlertTriangle, CheckCircle, ChevronDown, ChevronLeft, ChevronRight } from 'lucide-react';
import type { AnalysisResult, CapturedImages } from '@/app/page';

interface Props {
  result: AnalysisResult;
  images: CapturedImages;
  onRetake: () => void;
}

const LEVEL_CONFIG = [
  { label: 'No Baldness',        color: '#14b8a6', bg: 'rgba(20,184,166,0.15)',  ring: '#14b8a6' },
  { label: 'Mild Thinning',      color: '#eab308', bg: 'rgba(234,179,8,0.15)',   ring: '#eab308' },
  { label: 'Moderate Hair Loss', color: '#f97316', bg: 'rgba(249,115,22,0.15)',  ring: '#f97316' },
  { label: 'Severe Baldness',    color: '#ef4444', bg: 'rgba(239,68,68,0.15)',   ring: '#ef4444' },
];

// ── Affected area region definitions per photo angle ─────────────────────────
// Each region is a relative ellipse: { cx, cy, rx, ry } in 0..1 of image dims,
// plus the severity key and label.

type Region = {
  cx: number; cy: number;
  rx: number; ry: number;
  key: keyof AnalysisResult['affected_areas'];
  label: string;
};

const ANGLE_REGIONS: Record<string, Region[]> = {
  front: [
    { cx: 0.50, cy: 0.12, rx: 0.28, ry: 0.10, key: 'front',        label: 'Frontal' },
    { cx: 0.18, cy: 0.20, rx: 0.13, ry: 0.12, key: 'left_temple',  label: 'L Temple' },
    { cx: 0.82, cy: 0.20, rx: 0.13, ry: 0.12, key: 'right_temple', label: 'R Temple' },
  ],
  left: [
    { cx: 0.52, cy: 0.12, rx: 0.30, ry: 0.10, key: 'top',         label: 'Top'     },
    { cx: 0.25, cy: 0.18, rx: 0.16, ry: 0.12, key: 'left_temple', label: 'Temple'  },
    { cx: 0.50, cy: 0.22, rx: 0.24, ry: 0.10, key: 'crown',       label: 'Crown'   },
  ],
  right: [
    { cx: 0.48, cy: 0.12, rx: 0.30, ry: 0.10, key: 'top',          label: 'Top'    },
    { cx: 0.75, cy: 0.18, rx: 0.16, ry: 0.12, key: 'right_temple', label: 'Temple' },
    { cx: 0.50, cy: 0.22, rx: 0.24, ry: 0.10, key: 'crown',        label: 'Crown'  },
  ],
  top: [
    { cx: 0.50, cy: 0.30, rx: 0.24, ry: 0.18, key: 'crown',  label: 'Crown' },
    { cx: 0.50, cy: 0.58, rx: 0.28, ry: 0.16, key: 'top',    label: 'Top'   },
    { cx: 0.50, cy: 0.16, rx: 0.22, ry: 0.10, key: 'front',  label: 'Front' },
  ],
};

function severityColor(pct: number): string {
  if (pct < 20)  return '#14b8a6'; // teal  — negligible
  if (pct < 40)  return '#84cc16'; // lime  — mild
  if (pct < 60)  return '#eab308'; // yellow
  if (pct < 75)  return '#f97316'; // orange
  return '#ef4444';                 // red   — severe
}

// ── Canvas overlay component ──────────────────────────────────────────────────

function AnnotatedImage({
  src,
  angle,
  result,
  active,
}: {
  src: string;
  angle: string;
  result: AnalysisResult;
  active: boolean;
}) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const imgRef    = useRef<HTMLImageElement | null>(null);

  const draw = useCallback(() => {
    const canvas = canvasRef.current;
    if (!canvas || !imgRef.current) return;
    const img = imgRef.current;
    const W = canvas.width  = img.naturalWidth  || canvas.offsetWidth;
    const H = canvas.height = img.naturalHeight || canvas.offsetHeight;
    const ctx = canvas.getContext('2d')!;
    ctx.clearRect(0, 0, W, H);
    ctx.drawImage(img, 0, 0, W, H);

    const regions = ANGLE_REGIONS[angle] || [];

    for (const reg of regions) {
      const pct   = result.affected_areas[reg.key] ?? 0;
      if (pct < 5) continue; // skip negligible

      const color = severityColor(pct);
      const x  = reg.cx * W;
      const y  = reg.cy * H;
      const rx = reg.rx * W;
      const ry = reg.ry * H;

      // Fill ellipse with translucent colour
      ctx.save();
      ctx.beginPath();
      ctx.ellipse(x, y, rx, ry, 0, 0, Math.PI * 2);
      ctx.fillStyle   = color + '40'; // ~25% opacity
      ctx.strokeStyle = color + 'cc';
      ctx.lineWidth   = 2.5;
      ctx.setLineDash([]);
      ctx.fill();
      ctx.stroke();
      ctx.restore();

      // Label pill
      const label = `${reg.label} ${pct}%`;
      ctx.save();
      ctx.font         = `bold ${Math.round(W * 0.032)}px system-ui, sans-serif`;
      ctx.textBaseline = 'middle';
      const tw  = ctx.measureText(label).width;
      const ph  = W * 0.025;
      const pw  = tw + ph * 2;
      const lx  = x - pw / 2;
      const ly  = y - ry - ph * 2.4;

      // Pill background
      ctx.beginPath();
      ctx.roundRect(lx, ly, pw, ph * 2, ph);
      ctx.fillStyle = '#000000cc';
      ctx.fill();

      // Pill border
      ctx.beginPath();
      ctx.roundRect(lx, ly, pw, ph * 2, ph);
      ctx.strokeStyle = color + 'bb';
      ctx.lineWidth   = 1.5;
      ctx.stroke();

      // Text
      ctx.fillStyle = color;
      ctx.fillText(label, lx + ph, ly + ph);
      ctx.restore();

      // Corner dot
      ctx.beginPath();
      ctx.arc(x, y, W * 0.012, 0, Math.PI * 2);
      ctx.fillStyle = color;
      ctx.fill();
    }
  }, [angle, result]);

  useEffect(() => {
    const img  = new Image();
    img.onload = () => { imgRef.current = img; draw(); };
    img.src    = src;
  }, [src, draw]);

  return (
    <div className="relative w-full aspect-[4/3] rounded-2xl overflow-hidden bg-black/40">
      <canvas
        ref={canvasRef}
        className="w-full h-full object-cover"
        style={{ display: 'block' }}
      />
      {/* Angle badge */}
      <div className="absolute top-2 left-2 px-2.5 py-1 rounded-lg bg-black/60 backdrop-blur-sm">
        <span className="text-white/70 text-[10px] font-mono tracking-widest uppercase">{angle} view</span>
      </div>
    </div>
  );
}

// ── Image carousel (mobile‑friendly swipeable tabs) ───────────────────────────

function AnnotatedGallery({ images, result }: { images: CapturedImages; result: AnalysisResult }) {
  const available = (['front', 'left', 'right', 'top'] as const).filter(a => images[a]);
  const [idx, setIdx] = useState(0);

  if (available.length === 0) return null;

  const current = available[idx];

  return (
    <div className="glass rounded-2xl p-4">
      <h3 className="text-white font-semibold mb-3 flex items-center gap-2">
        <div className="w-1.5 h-4 rounded-full bg-plasma" />
        Baldness Area Map
        <span className="ml-auto text-white/30 text-xs font-mono">AI ANNOTATED</span>
      </h3>

      {/* Main annotated image */}
      <AnimatePresence mode="wait">
        <motion.div
          key={current}
          initial={{ opacity: 0, x: 12 }}
          animate={{ opacity: 1, x: 0 }}
          exit={{ opacity: 0, x: -12 }}
          transition={{ duration: 0.22 }}
        >
          <AnnotatedImage
            src={images[current]!}
            angle={current}
            result={result}
            active
          />
        </motion.div>
      </AnimatePresence>

      {/* Tabs */}
      <div className="flex gap-2 mt-3 justify-center">
        {available.map((a, i) => (
          <button
            key={a}
            onClick={() => setIdx(i)}
            className={`flex-1 py-2 rounded-xl text-xs font-mono tracking-wide transition-all ${
              i === idx
                ? 'bg-white/15 text-white'
                : 'bg-white/5 text-white/35 hover:bg-white/10'
            }`}
          >
            {a.toUpperCase()}
          </button>
        ))}
      </div>

      {/* Legend */}
      <div className="flex flex-wrap gap-x-3 gap-y-1.5 mt-3 px-1">
        {[
          { label: 'Low',      color: '#14b8a6', range: '<20%' },
          { label: 'Mild',     color: '#84cc16', range: '20–40%' },
          { label: 'Moderate', color: '#eab308', range: '40–60%' },
          { label: 'High',     color: '#f97316', range: '60–75%' },
          { label: 'Severe',   color: '#ef4444', range: '>75%' },
        ].map(l => (
          <div key={l.label} className="flex items-center gap-1.5">
            <div className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: l.color }} />
            <span className="text-white/40 text-[10px]">{l.label} <span className="text-white/25">({l.range})</span></span>
          </div>
        ))}
      </div>
    </div>
  );
}

// ── Score ring ────────────────────────────────────────────────────────────────

function ScoreRing({ score, level }: { score: number; level: number }) {
  const cfg  = LEVEL_CONFIG[level] || LEVEL_CONFIG[0];
  const r    = 70;
  const circ = 2 * Math.PI * r;
  const offset = circ * (1 - score / 100);

  return (
    <div className="relative w-48 h-48 mx-auto">
      <svg className="w-full h-full -rotate-90" viewBox="0 0 160 160">
        <circle cx="80" cy="80" r={r} fill="none" stroke="rgba(255,255,255,0.06)" strokeWidth="12" />
        <motion.circle
          cx="80" cy="80" r={r}
          fill="none"
          stroke={cfg.ring}
          strokeWidth="12"
          strokeDasharray={circ}
          strokeDashoffset={offset}
          strokeLinecap="round"
          initial={{ strokeDashoffset: circ }}
          animate={{ strokeDashoffset: offset }}
          transition={{ duration: 1.5, ease: 'easeOut', delay: 0.3 }}
        />
      </svg>
      <div className="absolute inset-0 flex flex-col items-center justify-center">
        <motion.span
          className="font-display text-4xl font-bold"
          style={{ color: cfg.ring }}
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.5 }}
        >
          {score}
        </motion.span>
        <span className="text-white/40 text-xs font-mono">BALDNESS SCORE</span>
      </div>
    </div>
  );
}

// ── Heatmap bar ───────────────────────────────────────────────────────────────

function HeatmapArea({ label, value, color }: { label: string; value: number; color: string }) {
  return (
    <div className="flex items-center gap-3">
      <span className="text-white/50 text-xs w-24 text-right">{label}</span>
      <div className="flex-1 h-2 bg-white/5 rounded-full overflow-hidden">
        <motion.div
          className="h-full rounded-full"
          style={{ backgroundColor: color }}
          initial={{ width: 0 }}
          animate={{ width: `${value}%` }}
          transition={{ duration: 1, delay: 0.8, ease: 'easeOut' }}
        />
      </div>
      <span className="font-mono text-xs w-8" style={{ color }}>{value}%</span>
    </div>
  );
}

function getAreaColor(value: number) {
  if (value < 25) return '#14b8a6';
  if (value < 50) return '#eab308';
  if (value < 75) return '#f97316';
  return '#ef4444';
}

// ── Main dashboard ────────────────────────────────────────────────────────────

export default function ResultsDashboard({ result, images, onRetake }: Props) {
  const [showInsights, setShowInsights] = useState(false);
  const cfg = LEVEL_CONFIG[result.classification_level] || LEVEL_CONFIG[0];

  const handleExport = () => {
    const reportText = `
ScalpAI Analysis Report
========================
Baldness Score:        ${result.baldness_score}/100
Hair Density:          ${result.hair_density_percentage}%
Classification:        ${result.classification}
Processing Time:       ${result.processing_time}s

Affected Areas:
  Top:                 ${result.affected_areas.top}%
  Crown:               ${result.affected_areas.crown}%
  Front:               ${result.affected_areas.front}%
  Left Temple:         ${result.affected_areas.left_temple}%
  Right Temple:        ${result.affected_areas.right_temple}%

AI Insights:
${result.ai_insights}

Recommendations:
${result.recommendations.map(r => `• ${r}`).join('\n')}

Generated by ScalpAI — ${new Date().toLocaleString()}
    `.trim();
    const blob = new Blob([reportText], { type: 'text/plain' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href = url; a.download = 'scalp-analysis.txt'; a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen pb-24">
      {/* Header */}
      <div className="glass border-b border-white/5 px-4 py-4 flex items-center justify-between">
        <span className="font-mono text-sm text-aurora-400 tracking-widest">ANALYSIS COMPLETE</span>
        <div className="flex gap-2">
          <button onClick={handleExport} className="p-2 rounded-xl glass hover:bg-white/10 transition-colors">
            <Download className="w-4 h-4 text-white/60" />
          </button>
          <button onClick={onRetake} className="flex items-center gap-2 px-3 py-2 rounded-xl glass hover:bg-white/10 transition-colors text-white/60 text-sm">
            <RotateCcw className="w-3.5 h-3.5" /> Retake
          </button>
        </div>
      </div>

      <div className="max-w-lg mx-auto px-4 py-6 space-y-6">

        {/* Score card */}
        <motion.div
          initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
          className="glass rounded-3xl p-6"
          style={{ borderColor: `${cfg.ring}30` }}
        >
          <ScoreRing score={result.baldness_score} level={result.classification_level} />
          <div className="text-center mt-4">
            <motion.div
              initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.6 }}
              className="inline-flex items-center gap-2 px-4 py-2 rounded-full text-sm font-semibold"
              style={{ background: cfg.bg, color: cfg.color }}
            >
              {result.classification_level === 0
                ? <CheckCircle className="w-4 h-4" />
                : <AlertTriangle className="w-4 h-4" />}
              {result.classification}
            </motion.div>
            <p className="text-white/30 text-xs font-mono mt-2">
              Processed in {result.processing_time}s
            </p>
          </div>
        </motion.div>

        {/* Stats row */}
        <motion.div
          initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15 }}
          className="grid grid-cols-2 gap-3"
        >
          <div className="glass rounded-2xl p-4">
            <Droplets className="w-5 h-5 text-aurora-400 mb-2" />
            <p className="text-2xl font-bold text-white">{result.hair_density_percentage}%</p>
            <p className="text-white/40 text-xs mt-1">Hair Density</p>
          </div>
          <div className="glass rounded-2xl p-4">
            <TrendingDown className="w-5 h-5 text-ember-400 mb-2" />
            <p className="text-2xl font-bold text-white">{result.baldness_score}</p>
            <p className="text-white/40 text-xs mt-1">Baldness Index</p>
          </div>
        </motion.div>

        {/* ★ Annotated photo gallery — NEW ★ */}
        <motion.div
          initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.22 }}
        >
          <AnnotatedGallery images={images} result={result} />
        </motion.div>

        {/* Affected areas heatmap */}
        <motion.div
          initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.28 }}
          className="glass rounded-2xl p-5"
        >
          <h3 className="text-white font-semibold mb-4 flex items-center gap-2">
            <div className="w-1.5 h-4 rounded-full bg-aurora-500" />
            Affected Areas
          </h3>
          <div className="space-y-3">
            {[
              { label: 'Top',          value: result.affected_areas.top          },
              { label: 'Crown',        value: result.affected_areas.crown        },
              { label: 'Front',        value: result.affected_areas.front        },
              { label: 'Left Temple',  value: result.affected_areas.left_temple  },
              { label: 'Right Temple', value: result.affected_areas.right_temple },
            ].map(a => (
              <HeatmapArea key={a.label} label={a.label} value={a.value} color={getAreaColor(a.value)} />
            ))}
          </div>
        </motion.div>

        {/* AI Insights */}
        <motion.div
          initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.35 }}
          className="glass rounded-2xl overflow-hidden"
        >
          <button
            className="w-full p-5 flex items-center justify-between"
            onClick={() => setShowInsights(!showInsights)}
          >
            <h3 className="text-white font-semibold flex items-center gap-2">
              <div className="w-1.5 h-4 rounded-full bg-plasma" />
              AI Vision Insights
            </h3>
            <ChevronDown className={`w-4 h-4 text-white/40 transition-transform ${showInsights ? 'rotate-180' : ''}`} />
          </button>
          {showInsights && (
            <motion.div
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: 'auto', opacity: 1 }}
              className="px-5 pb-5"
            >
              <p className="text-white/60 text-sm leading-relaxed">{result.ai_insights}</p>
            </motion.div>
          )}
        </motion.div>

        {/* Recommendations */}
        <motion.div
          initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.45 }}
          className="glass rounded-2xl p-5"
        >
          <h3 className="text-white font-semibold mb-4 flex items-center gap-2">
            <div className="w-1.5 h-4 rounded-full bg-ember-400" />
            Recommendations
          </h3>
          <div className="space-y-2">
            {result.recommendations.map((rec, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.5 + i * 0.08 }}
                className="flex items-start gap-3"
              >
                <div className="w-1.5 h-1.5 rounded-full bg-ember-400 mt-2 flex-shrink-0" />
                <p className="text-white/70 text-sm">{rec}</p>
              </motion.div>
            ))}
          </div>
          <p className="text-white/20 text-xs font-mono mt-4 leading-relaxed">
            NOT MEDICAL ADVICE. CONSULT A LICENSED DERMATOLOGIST FOR DIAGNOSIS & TREATMENT.
          </p>
        </motion.div>

      </div>
    </div>
  );
}